version: '2'
services:
  web:
    build: ./docker/web
    stdin_open: true
    restart: always
    tty: true
    volumes:
      - ./docker/web/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/web/fpm-pool.conf:/etc/php7/php-fpm.d/zzz_custom.conf
      - ./docker/web/php.ini:/etc/php7/conf.d/zzz_custom.ini
      - ./docker/web/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
      - ./:/var/www
    ports:
      - 80:80

  node:
    build: ./docker/node
    network_mode: host
    tty: false
    volumes:
      - ./:/var/www
